# Generated by Django 4.0.6 on 2022-08-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="yo'nalishi")),
            ],
            options={
                'verbose_name': "Yo'nalishi",
                'verbose_name_plural': "Yo'nalishi",
            },
        ),
        migrations.CreateModel(
            name='PropagandistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Targ'ibotchi")),
            ],
            options={
                'verbose_name': "Targ'ibotchi",
                'verbose_name_plural': "Targ'ibotchilar",
            },
        ),
        migrations.CreateModel(
            name='WhichLanguageWriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Qaysi tilda yozilgan')),
            ],
            options={
                'verbose_name': 'Yozilgan tili tanlsh',
                'verbose_name_plural': 'Yozilgan tili tanlash',
            },
        ),
        migrations.CreateModel(
            name='AclassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField()),
                ('issue', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pages', models.CharField(max_length=255)),
                ('article_pdf', models.FileField(blank=True, null=True, upload_to='article/')),
                ('open_air', models.URLField(max_length=255)),
                ('doi', models.URLField(max_length=255)),
                ('zenodo', models.URLField(max_length=255)),
                ('openair', models.URLField()),
                ('writer', models.CharField(max_length=255)),
                ('article_name', models.CharField(max_length=255)),
                ('annotation', models.CharField(max_length=255)),
                ('key_word', models.CharField(max_length=255)),
                ('literature', models.CharField(max_length=255)),
                ('handbook_document', models.ImageField(upload_to='images/document/')),
                ('greeting_card', models.ImageField(upload_to='images/greeting_card/')),
                ('handbook', models.ImageField(upload_to='images/handbook/')),
                ('certificate', models.ImageField(upload_to='images/certificate/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.fieldmodel', verbose_name="Yo'nalishi")),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.whichlanguagewritemodel')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.propagandistmodel')),
            ],
            options={
                'verbose_name': 'A seriya',
                'verbose_name_plural': 'A seriya',
            },
        ),
    ]
