# Generated by Django 4.1.1 on 2022-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='google',
            field=models.URLField(verbose_name='Google Schoolar'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='openair',
            field=models.URLField(verbose_name='OpenAire'),
        ),
    ]
