# Generated by Django 4.1 on 2022-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Tabriknoma'),
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Tabriknoma'),
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Tabriknoma'),
        ),
    ]
