# Generated by Django 4.0.6 on 2022-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aclassmodel',
            name='open_air',
        ),
    ]
