# Generated by Django 4.1.1 on 2022-11-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_aclassmodel_google_alter_aclassmodel_openair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='article_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='article/', verbose_name='Maqola (pdf)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/certificate/', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/handbook/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/document/', verbose_name='Mualliflik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='article_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='article/', verbose_name='Maqola (pdf)'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/certificate/', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/handbook/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/document/', verbose_name='Mualliflik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='article_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='article/', verbose_name='Maqola (pdf)'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/certificate/', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/handbook/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/document/', verbose_name='Mualliflik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='article_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='article/', verbose_name='Maqola (pdf)'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/certificate/', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/greeting_card/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/handbook/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/document/', verbose_name='Mualliflik Guvohnomasi'),
        ),
    ]
