# Generated by Django 4.1 on 2022-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_aclassmodel_greeting_card2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, null=True, upload_to='images/greeting_card/', verbose_name='Diplom4'),
        ),
    ]
