# Generated by Django 4.0.6 on 2022-08-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_aclassmodel_open_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Seriya',
                'verbose_name_plural': 'Seriyalar',
            },
        ),
        migrations.RemoveField(
            model_name='aclassmodel',
            name='handbook_document',
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='writer_document',
            field=models.ImageField(default=None, upload_to='images/document/', verbose_name='Mualliflik Guvohnomasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='annotation',
            field=models.CharField(max_length=255, verbose_name='Annotasiya (Asosiy til'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='article_name',
            field=models.CharField(max_length=255, verbose_name='Maqola nomi (Asosiy til)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='article_pdf',
            field=models.FileField(blank=True, null=True, upload_to='article/', verbose_name='Maqola (pdf)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='certificate',
            field=models.ImageField(upload_to='images/certificate/', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card',
            field=models.ImageField(upload_to='images/greeting_card/', verbose_name='Tabriknoma'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='handbook',
            field=models.ImageField(upload_to='images/handbook/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='key_word',
            field=models.CharField(max_length=255, verbose_name="Kalit so'zlar"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.whichlanguagewritemodel', verbose_name='Qaysi tilda yozilgan'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='literature',
            field=models.CharField(max_length=255, verbose_name='Adabiyotlar'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='pages',
            field=models.CharField(max_length=255, verbose_name='Sahifalar'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.propagandistmodel', verbose_name="Targ'ibotchi"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='writer',
            field=models.CharField(max_length=255, verbose_name='Mualliflar'),
        ),
    ]
