# Generated by Django 4.1 on 2023-07-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_aclassmodel_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='certificate', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='malumotnoma/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='guvohnoma/', verbose_name='Mualliflik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='certificate', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='malumotnoma/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='guvohnoma/', verbose_name='Mualliflik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='certificate', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='malumotnoma/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='guvohnoma/', verbose_name='Mualliflik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='certificate',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='certificate', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom2'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom3'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='greeting_card4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='diplom/', verbose_name='Diplom4'),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='handbook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='malumotnoma/', verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='writer_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='guvohnoma/', verbose_name='Mualliflik Guvohnomasi'),
        ),
    ]
