# Generated by Django 4.0.6 on 2022-08-14 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_categoryclassmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclassmodel',
            name='category_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='post.categoryclassmodel', verbose_name='Seriya'),
            preserve_default=False,
        ),
    ]
