# Generated by Django 4.0.6 on 2022-08-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_aclassmodel_category_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aclassmodel',
            name='category_class',
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='annotation',
            field=models.CharField(max_length=255, verbose_name='Annotasiya (Asosiy til)'),
        ),
        migrations.DeleteModel(
            name='CategoryClassModel',
        ),
    ]
