# Generated by Django 4.1 on 2022-10-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_dclassmodel_cclassmodel_bclassmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="yo'nalishi")),
            ],
            options={
                'verbose_name': "B seriya Yo'nalishi",
                'verbose_name_plural': "B seriya Yo'nalishi",
            },
        ),
        migrations.CreateModel(
            name='CFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="yo'nalishi")),
            ],
            options={
                'verbose_name': "C seriya Yo'nalishi",
                'verbose_name_plural': "C seriya Yo'nalishi",
            },
        ),
        migrations.CreateModel(
            name='DFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="yo'nalishi")),
            ],
            options={
                'verbose_name': "D seriya Yo'nalishi",
                'verbose_name_plural': "D seriya Yo'nalishi",
            },
        ),
        migrations.RenameModel(
            old_name='FieldModel',
            new_name='AFieldModel',
        ),
        migrations.AlterModelOptions(
            name='afieldmodel',
            options={'verbose_name': "A seriya Yo'nalishi", 'verbose_name_plural': "A seriya Yo'nalishi"},
        ),
        migrations.AlterModelOptions(
            name='bclassmodel',
            options={'verbose_name': 'B seriya', 'verbose_name_plural': 'B seriya'},
        ),
        migrations.AlterModelOptions(
            name='cclassmodel',
            options={'verbose_name': 'C seriya', 'verbose_name_plural': 'C seriya'},
        ),
        migrations.AlterModelOptions(
            name='dclassmodel',
            options={'verbose_name': 'D seriya', 'verbose_name_plural': 'D seriya'},
        ),
        migrations.AlterField(
            model_name='bclassmodel',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.bfieldmodel', verbose_name="Yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='cclassmodel',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.cfieldmodel', verbose_name="Yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='dclassmodel',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='post.dfieldmodel', verbose_name="Yo'nalishi"),
        ),
    ]
