# Generated by Django 5.0.3 on 2024-03-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_aclassmodel_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
