# Generated by Django 4.1 on 2022-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_aclassmodel_category_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aclassmodel',
            old_name='annotation',
            new_name='annotation_en',
        ),
        migrations.RenameField(
            model_name='aclassmodel',
            old_name='article_name',
            new_name='article_name_en',
        ),
        migrations.RenameField(
            model_name='aclassmodel',
            old_name='key_word',
            new_name='key_word_en',
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='annotation_ru',
            field=models.CharField(default=None, max_length=255, verbose_name='Annotasiya (Asosiy til)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='annotation_uz',
            field=models.CharField(default=None, max_length=255, verbose_name='Annotasiya (Asosiy til)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='article_name_ru',
            field=models.CharField(default=None, max_length=255, verbose_name='Maqola nomi (Asosiy til)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='article_name_uz',
            field=models.CharField(default=None, max_length=255, verbose_name='Maqola nomi (Asosiy til)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='key_word_ru',
            field=models.CharField(default=None, max_length=255, verbose_name="Kalit so'zlar"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='key_word_uz',
            field=models.CharField(default=None, max_length=255, verbose_name="Kalit so'zlar"),
            preserve_default=False,
        ),
    ]
