# Generated by Django 4.1 on 2022-10-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_bfieldmodel_cfieldmodel_dfieldmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclassmodel',
            name='cyberleninka',
            field=models.URLField(default=1, max_length=255, verbose_name='Cyberleninka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='google',
            field=models.URLField(default=1, verbose_name='Google Schoolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aclassmodel',
            name='openaccess',
            field=models.URLField(default=1, max_length=255, verbose_name='OpenAccess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bclassmodel',
            name='cyberleninka',
            field=models.URLField(default=1, max_length=255, verbose_name='Cyberleninka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bclassmodel',
            name='google',
            field=models.URLField(default=1, verbose_name='Google Schoolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bclassmodel',
            name='openaccess',
            field=models.URLField(default=1, max_length=255, verbose_name='OpenAccess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cclassmodel',
            name='cyberleninka',
            field=models.URLField(default=1, max_length=255, verbose_name='Cyberleninka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cclassmodel',
            name='google',
            field=models.URLField(default=1, verbose_name='Google Schoolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cclassmodel',
            name='openaccess',
            field=models.URLField(default=1, max_length=255, verbose_name='OpenAccess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dclassmodel',
            name='cyberleninka',
            field=models.URLField(default=1, max_length=255, verbose_name='Cyberleninka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dclassmodel',
            name='google',
            field=models.URLField(default=1, verbose_name='Google Schoolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dclassmodel',
            name='openaccess',
            field=models.URLField(default=1, max_length=255, verbose_name='OpenAccess'),
            preserve_default=False,
        ),
    ]
