# Generated by Django 4.1 on 2022-08-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_annotation_aclassmodel_annotation_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='annotation_en',
            field=models.TextField(blank=True, verbose_name='Annotasiya (Asosiy til) (en)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='annotation_ru',
            field=models.TextField(blank=True, verbose_name='Annotasiya (Asosiy til) (ru)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='annotation_uz',
            field=models.TextField(blank=True, verbose_name='Annotasiya (Asosiy til) (uz)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='article_name_en',
            field=models.TextField(blank=True, verbose_name='Maqola nomi (Asosiy til) (en)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='article_name_ru',
            field=models.TextField(blank=True, verbose_name='Maqola nomi (Asosiy til) (ru)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='article_name_uz',
            field=models.TextField(blank=True, verbose_name='Maqola nomi (Asosiy til) (uz)'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='key_word_en',
            field=models.TextField(blank=True, verbose_name="Kalit so'zlar (en)"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='key_word_ru',
            field=models.TextField(blank=True, verbose_name="Kalit so'zlar (ru)"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='key_word_uz',
            field=models.TextField(blank=True, verbose_name="Kalit so'zlar (uz)"),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='literature',
            field=models.TextField(blank=True, verbose_name='Adabiyotlar'),
        ),
        migrations.AlterField(
            model_name='aclassmodel',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='post.propagandistmodel', verbose_name="Targ'ibotchi"),
        ),
    ]
