# Generated by Django 4.1 on 2022-08-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_aclassmodel_annotation_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclassmodel',
            name='promoter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='post.propagandistmodel', verbose_name="Targ'ibotchi"),
            preserve_default=False,
        ),
    ]
