# Generated by Django 4.1 on 2022-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('content_uz', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
            ],
        ),
    ]
