# Generated by Django 4.1.1 on 2022-11-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('issue', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/archive')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/author/')),
                ('content_uz', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
            ],
        ),
    ]
