# Generated by Django 4.1 on 2022-08-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='image',
            field=models.ImageField(default=None, upload_to='media/author/'),
            preserve_default=False,
        ),
    ]
