# Generated by Django 5.0.3 on 2024-03-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivemodel',
            name='file',
            field=models.FileField(default=1, upload_to='media/archives'),
            preserve_default=False,
        ),
    ]
