# Generated by Django 4.1 on 2022-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_authormodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('issue', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/archive')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
